name: release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: npm install

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
    
    - name: Update version
      run: "npm version ${{GITHUB_RUN_ID}}"

    - name: Package the VSIX
      run: npm run package

    - uses: actions/upload-artifact@v1
      with:
        name: "xray-beams-${{GITHUB_RUN_ID}}.vsix"
        path: "xray-beams-${{GITHUB_RUN_ID}}.vsix"
    
    - name: Publish
      if: success()
      run: npm run deploy
      env:
        VSCE_PAT: ${{secrets.VSCE_PAT}}
